# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fonting-awesome-ios-0616' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fonting-awesome-ios-0616

  pod 'FontAwesomeKit', '~> 2.2.0'
  pod 'CWStatusBarNotification', '~> 2.3.4'



end
